/**
 * THC CLASH schema — re-exports from the canonical root shared/schema.ts
 * This ensures both apps use the same table definitions and types.
 */
export {
  // Core tables
  users,
  leaderboard,
  lifetimeLeaderboard,
  playerProgress,
  aiAssistants,
  conversations,
  gameContext,
  achievements,
  userAchievements,
  completedMissions,

  // THC CLASH tables
  gameTypes,
  nftBonuses,
  adminCards,
  userCards,
  gameSessions,
  spellEffects,
  playerNftAnalysis,
  cardTrades,
  balanceTransactions,

  // Zod insert schemas
  insertUserSchema,
  insertLeaderboardSchema,
  insertLifetimeLeaderboardSchema,
  insertAiAssistantSchema,
  insertConversationSchema,
  insertGameContextSchema,
  insertAchievementSchema,
  insertUserAchievementSchema,
  insertCompletedMissionSchema,
  insertPlayerProgressSchema,
  insertUserCardSchema,
  insertPlayerNftAnalysisSchema,

  // Types
  type User,
  type InsertUser,
  type Leaderboard,
  type InsertLeaderboard,
  type LifetimeLeaderboard,
  type InsertLifetimeLeaderboard,
  type AiAssistant,
  type InsertAiAssistant,
  type Conversation,
  type InsertConversation,
  type GameContext,
  type InsertGameContext,
  type Achievement,
  type InsertAchievement,
  type UserAchievement,
  type InsertUserAchievement,
  type CompletedMission,
  type InsertCompletedMission,
  type PlayerProgress,
  type InsertPlayerProgress,
  type UserCard,
  type InsertUserCard,
  type AdminCard,
  type GameSession,
  type SpellEffect,
  type GameType,
  type NftBonus,
  type CardTrade,
  type BalanceTransaction,
  type InsertPlayerNftAnalysis,
  type PlayerNftAnalysis,
} from "../../shared/schema";
